#!/bin/bash
# Created by Qurius

# More colors here: https://gist.github.com/vratiu/9780109
White='\033[0;37m'
Lightblue='\033[0;94m'

# Help message
read -r -d '' help_message << EOM
-h		Prints this help message.
--fast		Modifies the nmap speed (-T5).

EOM

# Banner
printf ${Lightblue}

cat << EOF
_________________________________

frostscan v0.1 by qurius
_________________________________

EOF

printf ${White}


# Check if -h is on the cmdline
for i in "$@"
do
	if [[ "$i" == "-h" ]]
	then
		printf -- "$help_message\n\n"
		exit
	fi
done


# Help message.
if [ $# -ne 3 ]
then
	printf "Usage: $0 <host ip> <name of the box>\n\n"
	printf "Optional switch '--fast'. For more info user '-h' switch.\n\n"
	exit
fi


# Cmdline params.
host=$1
boxname=$2
fast_switch=$3


# Check if the IP is valid.
if [[ ! $host =~ ^(([1-9]?[0-9]|1[0-9][0-9]|2([0-4][0-9]|5[0-5]))\.){3}([1-9]?[0-9]|1[0-9][0-9]|2([0-4][0-9]|5[0-5]))$ ]]
then
	printf "[x] Enter valid IP address\n\n" >&2
	exit
fi


cat << EOM
Target:
$host

EOM


# Create directory for nmap results.
if [ ! -d "./nmap" ]
then
	mkdir nmap
	printf "[+] Created the nmap directory.\n"
fi

start=$(date +%s)

# Nmap full port scan
printf "[*] Running the full-port scan.\n"

if [ ! -z $fast_switch ]
then
	printf "[i] Fast switch on.\n"
	sudo nmap -sS -p- -T5 -oN nmap/$boxname-allports $host 1>/dev/null
else
	sudo nmap -sS -p- -oN nmap/$boxname-allports $host 1>/dev/null
fi


# Parsing the nmap full-port scan output
printf "[*] Parsing the nmap full-port scan output.\n"
open_ports=$(cat nmap/$boxname-allports | grep -i 'open' | cut -d '/' -f 1 | sed -z 's/\n/,/g') 1>/dev/null
open_ports=${open_ports::-1} # strip the last ','


# Nmap selected ports script scan
if [ ! -z $open_ports ]
then
	printf "[*] Running script scan on ports: $open_ports\n\n"
	sudo nmap -sC -sV -oA nmap/$boxname -p $open_ports $host 1>/dev/null
fi


# Cleanup
sudo rm nmap/$boxname-allports

printf "Files:\n"

for i in $(ls nmap/)
do
	printf "./nmap/$i\n"
done

end=$(date +%s)

time_elapsed=$((end-start))

printf "\n[+] Scanning of the target machine ($host) completed in $time_elapsed seconds.\n\n"

